general:
  confirm_operations: true
  plex_only: false
  limit_plex_results: 3
  limit_trakt_results: 3
  exclude_genre: animation, documentary,
  show_summary: true
  show_cast: true
  show_language: true
  show_imdb_rating: true
  show_imdb_link: true
  keep_logs: 10

paths:
  path_mappings: null
  platform: windows

plex:
  url: http://localhost:32400
  token: YOUR_PLEX_TOKEN
  TV_library_title: TV Shows
  add_label: true
  label_name: RecommendedShows
  remove_previous_recommendations: true

sonarr:
  url: http://localhost:8989
  api_key: YOUR_SONARR_API_KEY
  root_folder: P:\TV
  add_to_sonarr: true
  monitor: true
  monitor_option: none #all, none or firstSeason
  search_missing: true
  quality_profile: HD-1080p
  sonarr_tag: RecommendForPlex


trakt:
  access_token: 
  client_id: YOUR_TRAKT_CLIENT_ID
  client_secret: YOUR_TRAKT_CLIENT_SECRET
  sync_watch_history: true
 
TMDB:
  api_key: YOUR_TMDB_API_KEY
  use_TMDB_keywords: true

weights: #Make sure the total equals 1
  genre_weight: 0.25
  keyword_weight: 0.25
  studio_weight: 0.20
  actor_weight: 0.20
  language_weight: 0.10