general:
  confirm_operations: true
  plex_only: false
  combine_watch_history: false
  limit_plex_results: 3
  limit_trakt_results: 3
  exclude_genre: none
  randomize_recommendations: true
  normalize_counters: true
  show_summary: true
  show_cast: true
  show_language: true
  show_rating: true
  show_imdb_link: true
  keep_logs: 10

paths:
  path_mappings: null
  platform: windows

plex:
  url: http://localhost:32400
  token: YOUR_PLEX_TOKEN
  TV_library_title: TV Shows
  managed_users: Admin
  add_label: true
  label_name: RecommendedShows
  append_usernames: true
  remove_previous_recommendations: true

sonarr:
  url: http://localhost:8989
  api_key: YOUR_SONARR_API_KEY
  root_folder: P:\TV
  add_to_sonarr: true
  monitor: true
  monitor_option: none #all, none or firstSeason
  search_missing: true
  quality_profile: HD-1080p
  sonarr_tag: RecommendForPlex

tautulli:
  api_key: YOUR_TAUTULLI_API_KEY
  url: http://localhost:8181
  users: none #Entering tautulli users will override managed_users!

trakt:
  access_token: 
  client_id: YOUR_TRAKT_CLIENT_ID
  client_secret: YOUR_TRAKT_CLIENT_SECRET
  clear_watch_history: false
  sync_watch_history: false
 
TMDB:
  api_key: YOUR_TMDB_API_KEY

weights: #Make sure the total equals 1
  genre_weight: 0.25
  keyword_weight: 0.25
  studio_weight: 0.20
  actor_weight: 0.20
  language_weight: 0.10